STATES = {
    'Andaman And Nicobar': 'Andaman And Nicobar',
    'Andhra Pradesh': 'Andhra Pradesh',
    'Arunachal Pradesh': 'Arunachal Pradesh',
    'Assam': 'Assam',
    'Bihar': 'Bihar',
    'Chandigarh': 'Chandigarh',
    'Chhattisgarh': 'Chhattisgarh',
    'Dadra And Nagar Haveli': 'Dadra And Nagar Haveli',
    'Daman And Diu': 'Daman And Diu',
    'Delhi':  'Delhi',
    'Goa': 'Goa',
    'Gujarat': 'Gujarat',
    'Haryana': 'Haryana',
    'Himachal Pradesh': 'Himachal Pradesh',
    'Jammu And Kashmir': 'Jammu And Kashmir',
    'Jharkhand': 'Jharkhand',
    'Karnataka': 'Karnataka',
    'Kerala': 'Kerala',
    'Madhya Pradesh': 'Madhya Pradesh',
    'Maharashtra': 'Maharashtra',
    'Manipur': 'Manipur',
    'Meghalaya': 'Meghalaya',
    'Mizoram': 'Mizoram',
    'Nagaland': 'Nagaland',
    'Odisha': 'Odisha',
    'Puducherry': 'Puducherry',
    'Punjab':  'Punjab',
    'Rajasthan': 'Rajasthan',
    'Sikkim':  'Sikkim',
    'Tamil Nadu': 'Tamil Nadu',
    'Telangana': 'Telangana',
    'Tripura': 'Tripura',
    'Uttar Pradesh': 'Uttar Pradesh',
    'Uttarakhand':  'Uttarakhand',
    'West Bengal': 'West Bengal',
}

CITIES = {
    'Andaman And Nicobar': {
        'Nicobar': 'Nicobar',
        'North And Middle Andaman': 'North And Middle Andaman',
        'South Andaman': 'South Andaman',

    },
    'Andhra Pradesh': {
        'Anantapur': 'Anantapur',
        'Chittoor': 'Chittoor',
        'Cuddapah': 'Cuddapah',
        'East Godavari': 'East Godavari',
        'Guntur': 'Guntur',
        'Krishna': 'Krishna',
        'Kurnool': 'Kurnool',
        'Nellore': 'Nellore',
        'Prakasam': 'Prakasam',
        'Srikakulam': 'Srikakulam',
        'Vishakhapatnam': 'Vishakhapatnam',
        'Vizianagaram': 'Vizianagaram',
        'West Godavari': 'West Godavari',

    },
    'Arunachal Pradesh': {
        'Changlang': 'Changlang',
        'Dibang Valley': 'Dibang Valley',
        'East Khameng': 'East Khameng',
        'East Siang': 'East Siang',
        'Lohit': 'Lohit',
        'Longding': 'Longding',
        'Lower Dibang Valley': 'Lower Dibang Valley',
        'Lower Subansiri': 'Lower Subansiri',
        'Namsai': 'Namsai',
        'Papumpare': 'Papumpare',
        'Tawang': 'Tawang',
        'Tirap': 'Tirap',
        'Upper Siang': 'Upper Siang',
        'Upper Sibansiri': 'Upper Sibansiri',
        'West Kameng': 'West Kameng',
        'West Siang': 'West Siang',
    },
    'Assam': {
        'Baksa': 'Baksa',
        'Barpeta': 'Barpeta',
        'Biswanath': 'Biswanath',
        'Bongaigaon': 'Bongaigaon',
        'Cachar': 'Cachar',
        'Charaideo': 'Charaideo',
        'Chirang': 'Chirang',
        'Darrang': 'Darrang',
        'Dhemaji': 'Dhemaji',
        'Dhuburi': 'Dhuburi',
        'Dibrugarh': 'Dibrugarh',
        'Dima Hasao': 'Dima Hasao',
        'Goalpara': 'Goalpara',
        'Golaghat': 'Golaghat',
        'Hailakandi': 'Hailakandi',
        'Hojai': 'Hojai',
        'Jorhat': 'Jorhat',
        'Kamrup': 'Kamrup',
        'Kamrup Metro': 'Kamrup Metro',
        'Karbi Anglong': 'Karbi Anglong',
        'Karimganj': 'Karimganj',
        'Kokrajhar': 'Kokrajhar',
        'Lakhimpur': 'Lakhimpur',
        'Majuli': 'Majuli',
        'Morigaon': 'Morigaon',
        'Nagaon': 'Nagaon',
        'Nalbari': 'Nalbari',
        'Sibsagar': 'Sibsagar',
        'Sonitpur': 'Sonitpur',
        'Tinsukia': 'Tinsukia',
        'Udalguri': 'Udalguri',
        'West Karbi Anglong': 'West Karbi Anglong',
    },
    'Bihar': {
        'Araria': 'Araria',
        'Arwal': 'Arwal',
        'Aurangabad': 'Aurangabad',
        'Banka': 'Banka',
        'Begusarai': 'Begusarai',
        'Bhagalpur': 'Bhagalpur',
        'Bhojpur': 'Bhojpur',
        'Buxar': 'Buxar',
        'Darbhanga': 'Darbhanga',
        'East Champaran': 'East Champaran',
        'Gaya': 'Gaya',
        'Gopalganj': 'Gopalganj',
        'Jahanabad': 'Jahanabad',
        'Jamui': 'Jamui',
        'Kaimur': 'Kaimur',
        'Katihar': 'Katihar',
        'Khagaria': 'Khagaria',
        'Kishanganj': 'Kishanganj',
        'Luckeesarai': 'Luckeesarai',
        'Madhepura': 'Madhepura',
        'Madhubani': 'Madhubani',
        'Munger': 'Munger',
        'Muzaffarpur': 'Muzaffarpur',
        'Nalanda': 'Nalanda',
        'Nawada': 'Nawada',
        'Patna': 'Patna',
        'Purnia': 'Purnia',
        'Rohtas': 'Rohtas',
        'Saharsa': 'Saharsa',
        'Samastipur': 'Samastipur',
        'Saran': 'Saran',
        'Sewan': 'Sewan',
        'Sheikhpura': 'Sheikhpura',
        'Sheohar': 'Sheohar',
        'Sitamarhi': 'Sitamarhi',
        'Supaul': 'Supaul',
        'Vaishali': 'Vaishali',
        'West Champaran': 'West Champaran',
    },
    'Chandigarh': {
        'Chandigarh': 'Chandigarh'
    },
    'Chhattisgarh': {
        'Balod': 'Balod',
        'Balodabazar': 'Balodabazar',
        'Balrampur': 'Balrampur',
        'Bastar': 'Bastar',
        'Bemetara': 'Bemetara',
        'Bijapur': 'Bijapur',
        'Bilaspur': 'Bilaspur',
        'Dantewada': 'Dantewada',
        'Dhamtari': 'Dhamtari',
        'Durg': 'Durg',
        'Gariyaband': 'Gariyaband',
        'Janjgir': 'Janjgir',
        'Jashpur': 'Jashpur',
        'Kanker': 'Kanker',
        'Kawardha': 'Kawardha',
        'Kondagaon': 'Kondagaon',
        'Korba': 'Korba',
        'Koria': 'Koria',
        'Mahasamund': 'Mahasamund',
        'Mungeli': 'Mungeli',
        'Raigarh': 'Raigarh',
        'Raipur': 'Raipur',
        'Rajnandgaon': 'Rajnandgaon',
        'Sukma': 'Sukma',
        'Surajpur': 'Surajpur',
        'Surguja': 'Surguja',
    },
    'Dadra And Nagar Haveli': {
        'Silvassa': 'Silvassa'
    },
    'Daman And Diu': {
        'Daman': 'Daman',
        'Diu': 'Diu'
    },
    'Delhi':  {
        'Central Delhi': 'Central Delhi',
        'Delhi Shahdara': 'Delhi Shahdara',
        'East Delhi': 'East Delhi',
        'New Delhi': 'New Delhi',
        'North Delhi': 'North Delhi',
        'North East Delhi': 'North East Delhi',
        'North West Delhi': 'North West Delhi',
        'South Delhi': 'South Delhi',
        'South East Delhi': 'South East Delhi',
        'South West Delhi': 'South West Delhi',
        'West Delhi': 'West Delhi',
    },
    'Goa': {
        'North Goa': 'North Goa',
        'South Goa': 'South Goa'
    },
    'Gujarat': {
        'Ahmedabad': 'Ahmedabad',
        'Amreli': 'Amreli',
        'Anand': 'Anand',
        'Aravalli': 'Aravalli',
        'Banas Kantha': 'Banas Kantha',
        'Bharuch': 'Bharuch',
        'Bhavnagar': 'Bhavnagar',
        'Botad': 'Botad',
        'Chhotaudepur': 'Chhotaudepur',
        'Dahod': 'Dahod',
        'Devbhumi Dwarka': 'Devbhumi Dwarka',
        'Gandhi Nagar': 'Gandhi Nagar',
        'Gir Somnath': 'Gir Somnath',
        'Jamnagar': 'Jamnagar',
        'Junagadh': 'Junagadh',
        'Kheda': 'Kheda',
        'Kutch': 'Kutch',
        'Mahisagar': 'Mahisagar',
        'Mehsana': 'Mehsana',
        'Morbi': 'Morbi',
        'Narmada': 'Narmada',
        'Navsari': 'Navsari',
        'Panch Mahal': 'Panch Mahal',
        'Patan': 'Patan',
        'Porbander': 'Porbander',
        'Rajkot': 'Rajkot',
        'Sabar Kantha': 'Sabar Kantha',
        'Surat': 'Surat',
        'Surendranagar': 'Surendranagar',
        'Tapi': 'Tapi',
        'The Dangs': 'The Dangs',
        'Vadodara': 'Vadodara',
        'Valsad': 'Valsad',
    },
    'Haryana': {
        'Ambala': 'Ambala',
        'Bhiwani': 'Bhiwani',
        'Charki Dadri': 'Charki Dadri',
        'Faridabad': 'Faridabad',
        'Fatehabad': 'Fatehabad',
        'Gurgaon': 'Gurgaon',
        'Hisar': 'Hisar',
        'Jhajjar': 'Jhajjar',
        'Jind': 'Jind',
        'Kaithal': 'Kaithal',
        'Karnal': 'Karnal',
        'Kurukshetra': 'Kurukshetra',
        'Mahendragarh': 'Mahendragarh',
        'Mewat': 'Mewat',
        'Palwal': 'Palwal',
        'Panchkula': 'Panchkula',
        'Panipat': 'Panipat',
        'Rewari': 'Rewari',
        'Rohtak': 'Rohtak',
        'Sirsa': 'Sirsa',
        'Sonipat': 'Sonipat',
        'Yamunanagar': 'Yamunanagar',
    },
    'Himachal Pradesh': {
        'Bilaspur': 'Bilaspur',
        'Chamba': 'Chamba',
        'Hamirpur': 'Hamirpur',
        'Kangra': 'Kangra',
        'Kinnaur': 'Kinnaur',
        'Kullu': 'Kullu',
        'Lahul Spiti': 'Lahul Spiti',
        'Mandi': 'Mandi',
        'Shimla': 'Shimla',
        'Sirmaur': 'Sirmaur',
        'Solan': 'Solan',
        'Una': 'Una',
    },
    'Jammu And Kashmir': {
        'Anantnag': 'Anantnag',
        'Badgam': 'Badgam',
        'Bandipora': 'Bandipora',
        'Baramullah': 'Baramullah',
        'Doda': 'Doda',
        'Ganderbal': 'Ganderbal',
        'Jammu': 'Jammu',
        'Kargil': 'Kargil',
        'Kathua': 'Kathua',
        'Kishtwar': 'Kishtwar',
        'Kulgam': 'Kulgam',
        'Kupwara': 'Kupwara',
        'Leh': 'Leh',
        'Poonch': 'Poonch',
        'Pulwama': 'Pulwama',
        'Rajouri': 'Rajouri',
        'Ramban': 'Ramban',
        'Reasi': 'Reasi',
        'Samba': 'Samba',
        'Shopian': 'Shopian',
        'Srinagar': 'Srinagar',
        'Udhampur': 'Udhampur',
    },
    'Jharkhand': {
        'Bokaro': 'Bokaro',
        'Chatra': 'Chatra',
        'Deogarh': 'Deogarh',
        'Dhanbad': 'Dhanbad',
        'Dumka': 'Dumka',
        'East Singhbhum': 'East Singhbhum',
        'Garhwa': 'Garhwa',
        'Giridih': 'Giridih',
        'Godda': 'Godda',
        'Gumla': 'Gumla',
        'Hazaribagh': 'Hazaribagh',
        'Jamtara': 'Jamtara',
        'Khunti': 'Khunti',
        'Koderma': 'Koderma',
        'Latehar': 'Latehar',
        'Lohardaga': 'Lohardaga',
        'Pakur': 'Pakur',
        'Palamau': 'Palamau',
        'Ramgarh': 'Ramgarh',
        'Ranchi': 'Ranchi',
        'Sahibganj': 'Sahibganj',
        'Saraikela Kharasawan': 'Saraikela Kharasawan',
        'Simdega': 'Simdega',
        'West Singhbhum': 'West Singhbhum',
    },
    'Karnataka': {
        'Bagalkot': 'Bagalkot',
        'Bangalore': 'Bangalore',
        'Bangalore Rural': 'Bangalore Rural',
        'Belgaum': 'Belgaum',
        'Bellary': 'Bellary',
        'Bidar': 'Bidar',
        'Bijapur': 'Bijapur',
        'Chamrajnagar': 'Chamrajnagar',
        'Chikkaballapura': 'Chikkaballapura',
        'Chikmagalur': 'Chikmagalur',
        'Chitradurga': 'Chitradurga',
        'Dakshin Kannad': 'Dakshin Kannad',
        'Davangere': 'Davangere',
        'Dharwad': 'Dharwad',
        'Gadag': 'Gadag',
        'Gulbarga': 'Gulbarga',
        'Hassan': 'Hassan',
        'Haveri': 'Haveri',
        'Kodagu': 'Kodagu',
        'Kolar': 'Kolar',
        'Koppal': 'Koppal',
        'Mandya': 'Mandya',
        'Mysore': 'Mysore',
        'Raichur': 'Raichur',
        'Ramanagara': 'Ramanagara',
        'Shimoga': 'Shimoga',
        'Tumkur': 'Tumkur',
        'Udupi': 'Udupi',
        'Uttar Kannad': 'Uttar Kannad',
        'Yadgir': 'Yadgir',
    },
    'Kerala': {
        'Alappuzha': 'Alappuzha',
        'Ernakulam': 'Ernakulam',
        'Idukki': 'Idukki',
        'Kannur': 'Kannur',
        'Kasaragod': 'Kasaragod',
        'Kollam': 'Kollam',
        'Kottayam': 'Kottayam',
        'Kozhikode': 'Kozhikode',
        'Malappuram': 'Malappuram',
        'Palakkad': 'Palakkad',
        'Pathananthitta': 'Pathananthitta',
        'Thiruvananthapuram': 'Thiruvananthapuram',
        'Thrissur': 'Thrissur',
        'Wayanad': 'Wayanad',
    },
    'Madhya Pradesh': {
        'Agar Malwa': 'Agar Malwa',
        'Alirajpur': 'Alirajpur',
        'Anupur': 'Anupur',
        'Ashoknagar': 'Ashoknagar',
        'Badwani': 'Badwani',
        'Balaghat': 'Balaghat',
        'Betul': 'Betul',
        'Bhind': 'Bhind',
        'Bhopal': 'Bhopal',
        'Burhanpur': 'Burhanpur',
        'Chhatarpur': 'Chhatarpur',
        'Chhindware': 'Chhindware',
        'Damoh': 'Damoh',
        'Datia': 'Datia',
        'Dewas': 'Dewas',
        'Dhar': 'Dhar',
        'Dindori': 'Dindori',
        'Guna': 'Guna',
        'Gwalior': 'Gwalior',
        'Harda': 'Harda',
        'Hoshangabad': 'Hoshangabad',
        'Indore': 'Indore',
        'Jabalpur': 'Jabalpur',
        'Jahbua': 'Jahbua',
        'Katni': 'Katni',
        'Khandwa': 'Khandwa',
        'Khargone': 'Khargone',
        'Mandla': 'Mandla',
        'Mandsaur': 'Mandsaur',
        'Morena': 'Morena',
        'Narsimhapur': 'Narsimhapur',
        'Neemach': 'Neemach',
        'Panna': 'Panna',
        'Raisen': 'Raisen',
        'Rajgarh': 'Rajgarh',
        'Ratlam': 'Ratlam',
        'Rewa': 'Rewa',
        'Sagar': 'Sagar',
        'Satna': 'Satna',
        'Sehore': 'Sehore',
        'Seoni': 'Seoni',
        'Shahdol': 'Shahdol',
        'Shajapur': 'Shajapur',
        'Sheopur': 'Sheopur',
        'Shivpuri': 'Shivpuri',
        'Sidhi': 'Sidhi',
        'Singrauli': 'Singrauli',
        'Tikamgarh': 'Tikamgarh',
        'Ujjain': 'Ujjain',
        'Umaria': 'Umaria',
        'Vidisha': 'Vidisha',
    },
    'Maharashtra': {
        'Ahmadnagar': 'Ahmadnagar',
        'Akola': 'Akola',
        'Amravati': 'Amravati',
        'Aurangabad': 'Aurangabad',
        'Bhandara': 'Bhandara',
        'Bid': 'Bid',
        'Buldhana': 'Buldhana',
        'Chandrapur': 'Chandrapur',
        'Dhule': 'Dhule',
        'Gadchiroli': 'Gadchiroli',
        'Gondia': 'Gondia',
        'Greater Mumbai': 'Greater Mumbai',
        'Hingoli': 'Hingoli',
        'Jalgaon': 'Jalgaon',
        'Jalna': 'Jalna',
        'Kolhapur': 'Kolhapur',
        'Latur': 'Latur',
        'Mumbai City': 'Mumbai City',
        'Nagpur': 'Nagpur',
        'Nanded': 'Nanded',
        'Nandurbar': 'Nandurbar',
        'Nashik': 'Nashik',
        'Osmanabad': 'Osmanabad',
        'Palghar': 'Palghar',
        'Parbhani': 'Parbhani',
        'Pune': 'Pune',
        'Raigarh': 'Raigarh',
        'Ratnagiri': 'Ratnagiri',
        'Sangli': 'Sangli',
        'Satara': 'Satara',
        'Sindhudurg': 'Sindhudurg',
        'Solapur': 'Solapur',
        'Thane': 'Thane',
        'Wardha': 'Wardha',
        'Washim': 'Washim',
        'Yavatmal': 'Yavatmal',
    },
    'Manipur': {
        'Bishnupur': 'Bishnupur',
        'Chandel': 'Chandel',
        'Churachandpur': 'Churachandpur',
        'East Imphal': 'East Imphal',
        'Jiribam': 'Jiribam',
        'Kakching': 'Kakching',
        'Kangpokpi': 'Kangpokpi',
        'Noney': 'Noney',
        'Pherzawl': 'Pherzawl',
        'Senapati': 'Senapati',
        'Tamenglong': 'Tamenglong',
        'Tengnoupal': 'Tengnoupal',
        'Thoubal': 'Thoubal',
        'Ukhrul': 'Ukhrul',
        'West Imphal': 'West Imphal',
    },
    'Meghalaya': {
        'East Garo Hills': 'East Garo Hills',
        'East Jaintia Hills': 'East Jaintia Hills',
        'East Khasi Hills': 'East Khasi Hills',
        'Jaintia Hills': 'Jaintia Hills',
        'North Garo Hills': 'North Garo Hills',
        'Ri Bhoi': 'Ri Bhoi',
        'South Garo Hills': 'South Garo Hills',
        'Southwest Khasi Hils': 'Southwest Khasi Hils',
        'West Garo Hills': 'West Garo Hills',
        'West Khasi Hills': 'West Khasi Hills',
    },
    'Mizoram': {
        'Aizawl': 'Aizawl',
        'Champhai': 'Champhai',
        'Kolasib': 'Kolasib',
        'Lawngtlai': 'Lawngtlai',
        'Lunglei': 'Lunglei',
        'Mamit': 'Mamit',
        'Saiha': 'Saiha',
        'Serchhip': 'Serchhip',
    },
    'Nagaland': {
        'Dimapur': 'Dimapur',
        'Kiphere': 'Kiphere',
        'Kohima': 'Kohima',
        'Longleng': 'Longleng',
        'Mokokchung': 'Mokokchung',
        'Mon': 'Mon',
        'Peren': 'Peren',
        'Phek': 'Phek',
        'Tuensang': 'Tuensang',
        'Wokha': 'Wokha',
        'Zunheboto': 'Zunheboto',
    },
    'Odisha': {
        'Angul': 'Angul',
        'Baleshwar': 'Baleshwar',
        'Bargarh': 'Bargarh',
        'Bhadrak': 'Bhadrak',
        'Bolangir': 'Bolangir',
        'Boudh': 'Boudh',
        'Cuttack': 'Cuttack',
        'Deogarh': 'Deogarh',
        'Dhenkanal': 'Dhenkanal',
        'Gajapati': 'Gajapati',
        'Ganjam': 'Ganjam',
        'Jagatsinghpur': 'Jagatsinghpur',
        'Jajpur': 'Jajpur',
        'Jharsuguda': 'Jharsuguda',
        'Kalahandi': 'Kalahandi',
        'Kandhamal': 'Kandhamal',
        'Kendrapara': 'Kendrapara',
        'Keonjhar': 'Keonjhar',
        'Khordha': 'Khordha',
        'Koraput': 'Koraput',
        'Malkangiri': 'Malkangiri',
        'Mayurbhanj': 'Mayurbhanj',
        'Nabarangapur': 'Nabarangapur',
        'Nayagarh': 'Nayagarh',
        'Nuaparha': 'Nuaparha',
        'Puri': 'Puri',
        'Rayagada': 'Rayagada',
        'Sambalpur': 'Sambalpur',
        'Sonapur': 'Sonapur',
        'Sundargarh': 'Sundargarh',
    },
    'Puducherry': {
        'Karaikal': 'Karaikal',
        'Mahe': 'Mahe',
        'Pondicherry': 'Pondicherry',
        'Yanam': 'Yanam',
    },
    'Punjab':  {
        'Amritsar': 'Amritsar',
        'Barnala': 'Barnala',
        'Bathinda': 'Bathinda',
        'Faridkot': 'Faridkot',
        'Fatehgarh Sahib': 'Fatehgarh Sahib',
        'Fazilka': 'Fazilka',
        'Firozpur': 'Firozpur',
        'Gurdaspur': 'Gurdaspur',
        'Hoshiarpur': 'Hoshiarpur',
        'Jalandhar': 'Jalandhar',
        'Kapurthala': 'Kapurthala',
        'Ludhiana': 'Ludhiana',
        'Mansa': 'Mansa',
        'Moga': 'Moga',
        'Muktsar': 'Muktsar',
        'Pathankot': 'Pathankot',
        'Patiala': 'Patiala',
        'Rupnagar': 'Rupnagar',
        'Sangrur': 'Sangrur',
        'Sas Nagar': 'Sas Nagar',
        'Shd Bhagat Singh Ngr': 'Shd Bhagat Singh Ngr',
        'Tarn Taran': 'Tarn Taran',
    },
    'Rajasthan': {
        'Ajmer': 'Ajmer',
        'Alwar': 'Alwar',
        'Banswara': 'Banswara',
        'Baran': 'Baran',
        'Barmer': 'Barmer',
        'Bharatpur': 'Bharatpur',
        'Bhilwara': 'Bhilwara',
        'Bikaner': 'Bikaner',
        'Bundi': 'Bundi',
        'Chittaurgarh': 'Chittaurgarh',
        'Churu': 'Churu',
        'Dausa': 'Dausa',
        'Dhaulpur': 'Dhaulpur',
        'Dungarpur': 'Dungarpur',
        'Ganganagar': 'Ganganagar',
        'Hanumangarh': 'Hanumangarh',
        'Jaipur': 'Jaipur',
        'Jaisalmer': 'Jaisalmer',
        'Jalor': 'Jalor',
        'Jhalawar': 'Jhalawar',
        'Jhunjhunun': 'Jhunjhunun',
        'Jodhpur': 'Jodhpur',
        'Karauli': 'Karauli',
        'Kota': 'Kota',
        'Nagaur': 'Nagaur',
        'Pali': 'Pali',
        'Pratapgarh': 'Pratapgarh',
        'Rajsamand': 'Rajsamand',
        'Sawaimadhopur': 'Sawaimadhopur',
        'Sikar': 'Sikar',
        'Sirohi': 'Sirohi',
        'Tonk': 'Tonk',
        'Udaipur': 'Udaipur',
    },
    'Sikkim':  {
        'East District': 'East District',
        'North District': 'North District',
        'South District': 'South District',
        'West District': 'West District',
    },
    'Tamil Nadu': {
        'Ariyalur': 'Ariyalur',
        'Chennai': 'Chennai',
        'Coimbatore': 'Coimbatore',
        'Cuddalore': 'Cuddalore',
        'Dharmapuri': 'Dharmapuri',
        'Dindigul': 'Dindigul',
        'Erode': 'Erode',
        'Kanchipuram': 'Kanchipuram',
        'Kanniyakumari': 'Kanniyakumari',
        'Karur': 'Karur',
        'Krishnagiri': 'Krishnagiri',
        'Madurai': 'Madurai',
        'Nagapattinam': 'Nagapattinam',
        'Namakkal': 'Namakkal',
        'Nilgiris': 'Nilgiris',
        'Perambalur': 'Perambalur',
        'Pudukkottai': 'Pudukkottai',
        'Ramanathapuram': 'Ramanathapuram',
        'Salem': 'Salem',
        'Sivaganga': 'Sivaganga',
        'Teni': 'Teni',
        'Thanjavur': 'Thanjavur',
        'Thiruvarur': 'Thiruvarur',
        'Tiruchchirappalli': 'Tiruchchirappalli',
        'Tirunelveli': 'Tirunelveli',
        'Tirupur': 'Tirupur',
        'Tiruvallur': 'Tiruvallur',
        'Tiruvannamalai': 'Tiruvannamalai',
        'Tuticorin': 'Tuticorin',
        'Vellore': 'Vellore',
        'Viluppuram': 'Viluppuram',
        'Virudunagar': 'Virudunagar',
    },
    'Telangana': {
        'Adilabad': 'Adilabad',
        'Bhadradri Kothagudem': 'Bhadradri Kothagudem',
        'Hyderabad': 'Hyderabad',
        'Jagitial': 'Jagitial',
        'Jangaon': 'Jangaon',
        'Jayashankar Bhupalpa': 'Jayashankar Bhupalpa',
        'Jogulamba Gadwal': 'Jogulamba Gadwal',
        'Kamareddy': 'Kamareddy',
        'Karim Nagar': 'Karim Nagar',
        'Khammam': 'Khammam',
        'Komram Bheem Asifaba': 'Komram Bheem Asifaba',
        'Mahabubabad': 'Mahabubabad',
        'Mancherial': 'Mancherial',
        'Medak': 'Medak',
        'Medchal Malkajgiri': 'Medchal Malkajgiri',
        'Mehabubnagar': 'Mehabubnagar',
        'Mulugu': 'Mulugu',
        'Nagarkurnool': 'Nagarkurnool',
        'Nalgonda': 'Nalgonda',
        'Narayanpet': 'Narayanpet',
        'Nirmal': 'Nirmal',
        'Nizamabad': 'Nizamabad',
        'Peddapalli': 'Peddapalli',
        'Rajanna Sircilla': 'Rajanna Sircilla',
        'Rangareddi': 'Rangareddi',
        'Sangareddy': 'Sangareddy',
        'Siddipet': 'Siddipet',
        'Suryapet': 'Suryapet',
        'Vikarabad': 'Vikarabad',
        'Wanaparthy': 'Wanaparthy',
        'Warangal': 'Warangal',
        'Warangal Rural': 'Warangal Rural',
        'Yadadri Bhuvanagiri': 'Yadadri Bhuvanagiri',
    },
    'Tripura': {
        'Dhalai': 'Dhalai',
        'Gomati': 'Gomati',
        'Khowai': 'Khowai',
        'North Tripura': 'North Tripura',
        'Sepahijhala': 'Sepahijhala',
        'South Tripura': 'South Tripura',
        'Unakoti': 'Unakoti',
        'West Tripura': 'West Tripura',
    },
    'Uttar Pradesh': {
        'Agra': 'Agra',
        'Aligarh': 'Aligarh',
        'Allahabad': 'Allahabad',
        'Ambedkarnagar': 'Ambedkarnagar',
        'Amethi Csm Nagar': 'Amethi Csm Nagar',
        'Amroha': 'Amroha',
        'Auraiya': 'Auraiya',
        'Azamgarh': 'Azamgarh',
        'Baghpat': 'Baghpat',
        'Bahraich': 'Bahraich',
        'Ballia': 'Ballia',
        'Balrampur': 'Balrampur',
        'Banda': 'Banda',
        'Barabanki': 'Barabanki',
        'Bareilly': 'Bareilly',
        'Basti': 'Basti',
        'Bijnor': 'Bijnor',
        'Budaun': 'Budaun',
        'Bulandshahr': 'Bulandshahr',
        'Chandauli': 'Chandauli',
        'Chitrakut': 'Chitrakut',
        'Deoria': 'Deoria',
        'Etah': 'Etah',
        'Etawah': 'Etawah',
        'Faizabad': 'Faizabad',
        'Farrukkhabad': 'Farrukkhabad',
        'Fatehpur': 'Fatehpur',
        'Firozabad': 'Firozabad',
        'Gautam Budh Nagar': 'Gautam Budh Nagar',
        'Ghaziabad': 'Ghaziabad',
        'Ghazipur': 'Ghazipur',
        'Gonda': 'Gonda',
        'Gorakhpur': 'Gorakhpur',
        'Hamirpur': 'Hamirpur',
        'Hapur': 'Hapur',
        'Hardoi': 'Hardoi',
        'Hathras': 'Hathras',
        'Jalaun': 'Jalaun',
        'Jaunpur': 'Jaunpur',
        'Jhansi': 'Jhansi',
        'Kannuaj': 'Kannuaj',
        'Kanpur Rural': 'Kanpur Rural',
        'Kanpur Urban': 'Kanpur Urban',
        'Kashi Ram Nagar': 'Kashi Ram Nagar',
        'Kaushambi': 'Kaushambi',
        'Kushinagar': 'Kushinagar',
        'Lakhimpur': 'Lakhimpur',
        'Lalitpur': 'Lalitpur',
        'Lucknow': 'Lucknow',
        'Maharajganj': 'Maharajganj',
        'Mahoba': 'Mahoba',
        'Mainpuri': 'Mainpuri',
        'Mathura': 'Mathura',
        'Maunathbhanjan': 'Maunathbhanjan',
        'Meerut': 'Meerut',
        'Mirzapur': 'Mirzapur',
        'Moradabad': 'Moradabad',
        'Muzaffarnagar': 'Muzaffarnagar',
        'Pilibhit': 'Pilibhit',
        'Pratapgarh': 'Pratapgarh',
        'Rae Bareli': 'Rae Bareli',
        'Rampur': 'Rampur',
        'Saharanpur': 'Saharanpur',
        'Sambhal': 'Sambhal',
        'Sant Kabir Nagar': 'Sant Kabir Nagar',
        'Sant Ravi Nagar': 'Sant Ravi Nagar',
        'Shahjahanpur': 'Shahjahanpur',
        'Shamli': 'Shamli',
        'Shravasti': 'Shravasti',
        'Sidharthnagar': 'Sidharthnagar',
        'Sitapur': 'Sitapur',
        'Sonbhadra': 'Sonbhadra',
        'Sultanpur': 'Sultanpur',
        'Unnao': 'Unnao',
        'Varanasi': 'Varanasi',
    },
    'Uttarakhand':  {
        'Almora': 'Almora',
        'Bageshwar': 'Bageshwar',
        'Chamoli': 'Chamoli',
        'Champawat': 'Champawat',
        'Dehradun': 'Dehradun',
        'Haridwar': 'Haridwar',
        'Nainital': 'Nainital',
        'Pauri': 'Pauri',
        'Pithoragarh': 'Pithoragarh',
        'Rudraprayag': 'Rudraprayag',
        'Tehri Garhwal': 'Tehri Garhwal',
        'Udham Singh Nagar': 'Udham Singh Nagar',
        'Uttarkashi': 'Uttarkashi',
    },
    'West Bengal': {
        'Alipurduar': 'Alipurduar',
        'Bankura': 'Bankura',
        'Birbhum': 'Birbhum',
        'Cooch Bihar': 'Cooch Bihar',
        'Dakshin Dinajpur': 'Dakshin Dinajpur',
        'Darjeeling': 'Darjeeling',
        'Hooghly': 'Hooghly',
        'Howrah': 'Howrah',
        'Jalpaiguri': 'Jalpaiguri',
        'Jhargram': 'Jhargram',
        'Kalimpong': 'Kalimpong',
        'Kolkata': 'Kolkata',
        'Malda': 'Malda',
        'Murshidabad': 'Murshidabad',
        'Nadia': 'Nadia',
        'North 24 Parganas': 'North 24 Parganas',
        'Paschim Bardhaman': 'Paschim Bardhaman',
        'Paschim Medinipur': 'Paschim Medinipur',
        'Purba Bardhaman': 'Purba Bardhaman',
        'Purba Medinipur': 'Purba Medinipur',
        'Purulia': 'Purulia',
        'South 24 Parganas': 'South 24 Parganas',
        'Uttar Dinajpur': 'Uttar Dinajpur',
    },
}
